apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-app
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/0xMordecai/blog-environments.git
    targetRevision: dev
    path: application/
