apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-app
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/0xMordecai/blog-environments.git
    targetRevision: dev
    path: Manifest/application/
  destination:
    server: https://kubernetes.default.svc
    namespace: blog-app
  syncPolicy:
    automated:
      selfHeal: true
