apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-deployment
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-deployment
  template:
    metadata:
      labels:
        app: prometheus-deployment
    spec:
      containers:
      - image: prom/prometheus:v3.5.1
        name: prometheus
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
