name: Dev branch CD pipeline
on: 
  push:
    branches: [dev]
jobs:
  dev-environment-infrastructure:
    name: Create Environment
    uses: ./.github/workflows/create-cluster.yaml
    secrets: inherit
  set-up-argocd:
    name: Install argoCD
    needs: [dev-environment-infrastructure]
    uses: ./.github/workflows/install-argocd.yaml
    secrets: inherit